# dein.toml
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'bash install.sh'

# colorschemes
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'morhetz/gruvbox'
[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

# quickrun \r
[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

#[[plugins]]
#repo = 'andymass/vim-matchup'

### Language support

# Nim helper
#[[plugins]]
#repo = 'baabelfish/nvim-nim'
#[[plugins]]
#repo = "zah/nim.vim"

[[plugins]]
repo = 'mkanenobu/nvim-nim'

[[plugins]]
repo = 'hhvm/vim-hack'

[[plugins]]
repo = 'evidens/vim-twig'

[[plugins]]
repo = 'boeckmann/vim-freepascal'

[[plugins]]
repo = 'dag/vim2hs'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'eagletmt/neco-ghc'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'




[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

# Deoplete sources

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
