# dein.toml
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

# quickrun \r
[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

# Nim helper
#[[plugins]]
#repo = 'baabelfish/nvim-nim'
#[[plugins]]
#repo = "zah/nim.vim"
[[plugins]]
repo = 'mkanenobu/nvim-nim'

#[[plugins]]
#repo = 'thinca/vim-ref'

[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

# Deoplete sources

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'zchee/deoplete-jedi'

#[[plugins]]
#repo = 'padawan-php/deoplete-padawan'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'evidens/vim-twig'
