[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/vinarise.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'Shougo/neco-vim'

#()complete
#[[plugins]]
#repo = 'thinca/lexima.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mattn/flappyvird-vim'

