# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'SpaceVim/SpaceVim'





[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'zchee/deoplete-go'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'

[[plugins]]
repo = 'php-vim/phpcd.vim'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo = 'thalesmello/webcomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
