# dein.toml
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

#[[plugins]]
#repo = 'gisraptor/vim-lilypond-integrator'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

# quickrun \r
[[plugins]]
repo = 'thinca/vim-quickrun'

# git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Yggdroot/indentLine'
#[[plugins]]
#repo =  'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

# Nim helper
#[[plugins]]
#repo = 'baabelfish/nvim-nim'
#[[plugins]]
#repo = "zah/nim.vim"
[[plugins]]
repo = 'mkanenobu/nvim-nim'

[[plugins]]
repo = 'davidhalter/jedi-vim'

#[[plugins]]
#repo = 'alvan/vim-closetag'

# Linter
#[[plugins]]
#repo = 'neomake/neomake'
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

#[[plugins]]
#repo = 'roxma/nvim-yarp'
#
#[[plugins]]
#repo = 'roxma/vim-hug-neovim-rpc'

# Deoplete sources

#[[plugins]]
#repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
