# dein.toml
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

#[[plugins]]
#repo = 'gisraptor/vim-lilypond-integrator'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'

#[[plugins]]
#repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

# Comment helper <C-_>(C-_>
[[plugins]]
repo = 'tomtom/tcomment_vim'

# quickrun \r
[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

# Nim helper
[[plugins]]
repo = 'baabelfish/nvim-nim'
#[[plugins]]
#repo = "zah/nim.vim"

[[plugins]]
repo = 'alvan/vim-closetag'

# Linter
#[[plugins]]
#repo = 'neomake/neomake'
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

# Deoplete sources

#[[plugins]]
#repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'zchee/deoplete-go'

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
